FROM python:latest
#Image to use for Docker Image
WORKDIR /Users/Shared
#Estblish Working Directory
COPY swapi-challenge-3.py ./
COPY url_swapi.py ./
#Copy script files
CMD ["python3", "./swapi-challenge-3.py"]